### ISSUE TITLE
输入前缀没有提示 

### ISSUE THREAD

**Issue by weiShaoY** [vueuz/arco-design-vue-snippets#2]
![image](https://github.com/vueuz/arco-design-vue-snippets/assets/56295518/aa5cb239-bed1-497b-9e0e-b4f8470892d8)

**Comment by vueuz** [comment]
这个代码片段只有在vue或html文件格式下可以使用,如果是的话你可以试试重启vscode或者按ctrl + shift + p 然后输入reload window
